import type { Profile } from './types'

/**
 * The real content for zatwik.com. Authored once here and consumed by every
 * mode. Add a project = add one entry to the relevant group.
 *
 * Items marked "[…]" are placeholders carried over from the design mock —
 * fill them in with real details when available.
 */
export const profile: Profile = {
  name: 'Satwik Bhatnagar',
  tagline: 'Full-stack software engineer · London.',
  // Drop your real CV here: public/cv.pdf
  cvUrl: '/cv.pdf',
  contactEmail: 'sa7wik@gmail.com',
  socials: [
    {
      label: 'GitHub',
      icon: 'github',
      hint: 'zatwik511',
      action: { kind: 'link', url: 'https://github.com/zatwik511' },
    },
    {
      label: 'LinkedIn',
      icon: 'linkedin',
      // TODO: confirm the exact LinkedIn vanity URL / handle.
      hint: 'satwik-bhatnagar',
      action: { kind: 'link', url: 'https://www.linkedin.com/in/satwik-bhatnagar' },
    },
    {
      label: 'Phone',
      icon: 'phone',
      // TODO: replace with the real number.
      hint: '+44 0000 000000',
      action: { kind: 'copy', value: '+44 0000 000000' },
    },
    {
      label: 'Email',
      icon: 'email',
      hint: 'sa7wik@gmail.com',
      action: { kind: 'mailto', address: 'sa7wik@gmail.com' },
    },
  ],
  skills: [
    'TypeScript',
    'Python',
    'C++',
    'React',
    'Node.js',
    'PostgreSQL',
    'Three.js',
    'JavaScript',
    'Git',
    'HTML/CSS',
  ],
  nowPlaying: {
    track: 'Interstellar — Main Theme',
    artist: 'Hans Zimmer',
  },
  groups: [
    {
      heading: 'Education',
      entries: [
        {
          id: 'school',
          kind: 'education',
          navLabel: 'School',
          navBlurb: 'Where it all started',
          hudLabel: 'SCHOOL',
          title: '[Your school] · [years]',
          meta: '',
          body: 'Add your school, board, and any standout results or activities here.',
          universe: { galaxy: 'Education' },
        },
        {
          id: 'bachelors',
          kind: 'education',
          navLabel: "Bachelor's",
          navBlurb: 'Undergraduate degree',
          hudLabel: "BACHELOR’S",
          title: '[Degree] · [University] · [years]',
          meta: '',
          body: 'Add your undergraduate degree, focus area, and notable coursework.',
          universe: { galaxy: 'Education' },
        },
        {
          id: 'masters',
          kind: 'education',
          navLabel: "Master's",
          navBlurb: 'MSc · Kingston University London',
          hudLabel: "MASTER’S",
          title: 'MSc Software Engineering with Management Studies',
          meta: 'Kingston University London · 2025-26',
          body:
            'Dissertation: quantifying software-delivery pipeline bottlenecks (the LPBQ model).',
          universe: { galaxy: 'Education' },
        },
        {
          id: 'cert-aws',
          kind: 'education',
          navLabel: 'AWS Certified',
          navBlurb: 'Cloud Practitioner',
          hudLabel: 'AWS CERTIFICATION',
          title: 'AWS Certified Cloud Practitioner',
          meta: 'Amazon Web Services · [year]',
          body: 'Foundational certification covering AWS core services, security, and pricing.',
          universe: { galaxy: 'Education', system: 'Certificates' },
        },
        {
          id: 'cert-ml',
          kind: 'education',
          navLabel: 'ML Specialization',
          navBlurb: 'Online certificate',
          hudLabel: 'ML SPECIALIZATION',
          title: 'Machine Learning Specialization',
          meta: 'Coursera · [year]',
          body: 'Supervised learning, neural networks, and best practices for ML projects.',
          universe: { galaxy: 'Education', system: 'Certificates' },
        },
        {
          id: 'cert-sql',
          kind: 'education',
          navLabel: 'SQL Certificate',
          navBlurb: 'Database fundamentals',
          hudLabel: 'SQL CERTIFICATE',
          title: 'SQL & Databases',
          meta: '[provider] · [year]',
          body: 'Relational modelling, joins, indexing, and query optimisation.',
          universe: { galaxy: 'Education', system: 'Certificates' },
        },
      ],
    },
    {
      heading: 'Experience',
      entries: [
        {
          id: 'job1',
          kind: 'experience',
          navLabel: 'Software intern — [company]',
          navBlurb: 'Internship · [stack]',
          hudLabel: 'SOFTWARE INTERN',
          title: '[Company] · [dates]',
          meta: '',
          body: 'Add the role, the stack, and one or two things you shipped or improved.',
          universe: { galaxy: 'Experience' },
        },
        {
          id: 'job2',
          kind: 'experience',
          navLabel: 'Part-time — [role]',
          navBlurb: 'Freelance & client work',
          hudLabel: 'PART-TIME / FREELANCE',
          title: '[Role] · [dates]',
          meta: '',
          body: 'Add part-time work, freelance web builds, or client projects.',
          universe: { galaxy: 'Experience' },
        },
        {
          id: 'job3',
          kind: 'experience',
          navLabel: 'Software engineer — [company]',
          navBlurb: 'Full-time engineering role',
          hudLabel: 'SOFTWARE ENGINEER',
          title: '[Company] · [dates]',
          meta: '',
          body: 'Add the role, the stack, and one or two things you shipped or improved.',
          universe: { galaxy: 'Experience' },
        },
        {
          id: 'job4',
          kind: 'experience',
          navLabel: 'Open-source — [project]',
          navBlurb: 'Community contributions',
          hudLabel: 'OPEN SOURCE',
          title: '[Project] · [dates]',
          meta: '',
          body: 'Add notable open-source contributions, PRs merged, or maintainer roles.',
          universe: { galaxy: 'Experience' },
        },
        {
          id: 'job5',
          kind: 'experience',
          navLabel: 'Hackathon — [event]',
          navBlurb: 'Built in under 48 hours',
          hudLabel: 'HACKATHON',
          title: '[Event] · [placement]',
          meta: '',
          body: 'Add the hackathon, what you built, and how it placed.',
          universe: { galaxy: 'Experience' },
        },
        {
          id: 'job6',
          kind: 'experience',
          navLabel: 'Teaching assistant',
          navBlurb: 'Mentoring & demos',
          hudLabel: 'TEACHING ASSISTANT',
          title: '[Course] · [dates]',
          meta: '',
          body: 'Add the course, what you taught, and the class size.',
          universe: { galaxy: 'Experience' },
        },
      ],
    },
    {
      heading: 'Projects',
      entries: [
        {
          id: 'medisync',
          kind: 'project',
          navLabel: 'MediSync',
          navBlurb: 'Hospital management system',
          hudLabel: 'MEDISYNC',
          title: 'MediSync',
          summary: 'Full-stack hospital management system.',
          features:
            'Features: role-based access, appointment scheduling, records management, analytics dashboard. Feature-complete.',
          tech: ['TypeScript', 'Node.js', 'PostgreSQL'],
          media: [
            { type: 'video', caption: 'admin demo' },
            { type: 'image', caption: 'landing page' },
          ],
          link: { label: 'open MediSync', url: '#' },
          universe: { galaxy: 'Engineering', system: 'Web apps' },
        },
        {
          id: 'zathas',
          kind: 'project',
          navLabel: 'Zathas AI',
          navBlurb: 'Dual-mode AI chatbot',
          hudLabel: 'ZATHAS AI',
          title: 'Zathas AI',
          summary: 'Dual-mode AI chatbot.',
          features:
            'Public layer plus a hidden admin panel, GitHub-to-Render auto-deploy. A "Peter Parker / Spider-Man" public-vs-private architecture.',
          tech: ['Groq', 'Gemini', 'Node.js', 'Render'],
          media: [
            { type: 'video', caption: 'live demo' },
            { type: 'image', caption: 'admin panel' },
          ],
          link: { label: 'open Zathas AI', url: '#' },
          universe: { galaxy: 'Engineering', system: 'AI' },
        },
        {
          id: 'eval',
          kind: 'project',
          navLabel: 'Answer Eval',
          navBlurb: 'NLP answer scoring',
          hudLabel: 'ANSWER EVAL',
          title: 'Answer Eval',
          summary: 'Subjective answer evaluation.',
          features:
            'Scores free-text answers against a reference using semantic similarity and keyword analysis. In active development.',
          tech: ['Python', 'NLP', 'ML'],
          media: [
            { type: 'video', caption: 'demo run' },
            { type: 'image', caption: 'results view' },
          ],
          link: { label: 'open project', url: '#' },
          universe: { galaxy: 'Research', system: 'NLP' },
        },
        {
          id: 'pong',
          kind: 'project',
          navLabel: 'CV Ping Pong',
          navBlurb: 'Hand-tracked 3D pong',
          hudLabel: 'CV PING PONG',
          title: 'CV Ping Pong',
          summary: 'Hand-tracked 3D pong in the browser.',
          features:
            'Tracks your hand via webcam to control a paddle in a 3D scene. Vite + TypeScript stack.',
          tech: ['MediaPipe', 'Three.js', 'Vite', 'TypeScript'],
          media: [
            { type: 'video', caption: 'gameplay clip' },
            { type: 'image', caption: 'game screen' },
          ],
          link: { label: 'open game', url: '#' },
          universe: { galaxy: 'Creative', system: 'Games' },
        },
        {
          id: 'portfolio',
          kind: 'project',
          navLabel: 'zatwik.com',
          navBlurb: 'This spaceship portfolio',
          hudLabel: 'ZATWIK.COM',
          title: 'zatwik.com',
          summary: 'A spaceship-themed portfolio.',
          features:
            'A two-mode site: a static cockpit and a future 3D ride, both driven by one shared content source.',
          tech: ['React', 'TypeScript', 'Vite'],
          media: [
            { type: 'video', caption: 'cockpit demo' },
            { type: 'image', caption: 'landing' },
          ],
          link: { label: 'you are here', url: '#' },
          universe: { galaxy: 'Creative', system: 'Web' },
        },
        {
          id: 'sample-proj',
          kind: 'project',
          navLabel: '[Next project]',
          navBlurb: 'Coming soon',
          hudLabel: 'NEXT PROJECT',
          title: '[Your next project]',
          summary: 'Add your next build here.',
          features:
            'A placeholder card showing how new projects slot into the grid and paging.',
          tech: ['TBD'],
          media: [
            { type: 'video', caption: 'demo' },
            { type: 'image', caption: 'screenshot' },
          ],
          link: { label: 'open', url: '#' },
          universe: { galaxy: 'Engineering' },
        },
      ],
    },
  ],
}
